### ISSUE TITLE
Is one instance of traefik enough for multiple microservices?

### ISSUE THREAD

**Issue by rishighan** [moleculerjs/moleculer-web#152]
I have 4 microservices built on `moleculer` deployed using `docker-compose`

My `docker-compose` configuration for one service has the following dependencies:

1. `nats`
2. `zookeeper`
3. `traefik`

Now, for the other 3 microservices, should I define `1`, `2`, and `3` again? Or is it okay for me to just refer to them using Docker's `external_links`? What is the pattern for `nats` and `traefik` when you want to deploy multiple microservices ?

**Comment by intech** [comment]
@rishighan a transport server can be either one or several, but a cluster is created using the transport server of your choice and not moleculer.
To connect brokers with transport, you only need to make them available inside the docker network for the broker through .env or moleculer.config.js
It’s best to create a project using moleculer-cli and a standard [project template](https://github.com/moleculerjs/moleculer-template-project), where we take care of the modern and [correct configuration](https://github.com/moleculerjs/moleculer-template-project/blob/master/template/docker-compose.yml)

**Comment by rishighan** [comment]
Thanks @intech 

I have my project structure generated through `moleculer-cli` and I think during the prompts, I chose not to have Docker support, instead I copied the `docker-compose` configuration from the moleculer docs.

Here's `docker-compose.yml` for one of my microservices:
```yaml
version: "3.2"

services:

  api:
    build:
      context: .
    image: frishi/analytics-service-api
    container_name: analytics-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: frishi/analytics-service-greeter
    container_name: analytics-service-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: analytics
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
      - redis
    networks:
      - internal

  nats:
    image: nats
    container_name: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  redis:
    container_name: cache
    image: redis
    networks:
      - internal
    ports:
      - "6379:6379"
    volumes:
      - ../redis/data:/data
    entrypoint: redis-server --appendonly yes  
    restart: always
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - /path/to/zookeeper-persistence:/bitnami/zookeeper

  traefik:
    image: traefik:1.7
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:

```

Questions:

1. How do I make `nats` available to the other 3 microservices?
2. Should `traefik` configuration be replicated for all other microservices?

**Comment by rishighan** [comment]
I got the two services to `docker-compose` by:
1. Creating an external network
2. Connecting the second service to that external network.

However now, I can't hit any of those services at the ports I exposed for them. I am kind of stuck at this point. I think that my `traefik` configuration is incorrect. What do you think?

For posterity, here are the two `docker-compose.yml` files for `analytics-service` and `posts-service`:

```yaml
version: "3.2"

services:
  api:
    build:
      context: .
    image: frishi/analytics-service-api
    container_name: analytics-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
      - zookeeper
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - rgnetwork

  greeter:
    build:
      context: .
    image: frishi/analytics-service-greeter
    container_name: analytics-service-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: analytics
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
      - zookeeper
    networks:
      - rgnetwork

  nats:
    image: nats
    container_name: nats
    labels:
      - "traefik.enable=false"
    networks:
      - rgnetwork

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment: 
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - rgnetwork

  traefik:
    image: traefik:1.7
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - rgnetwork
      - default

networks:
  rgnetwork:
    driver: bridge

```

```yaml
version: "3.2"

services:
  posts-api:
    build:
      context: .
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: posts-api
      PORT: 5000
    depends_on: 
      - mongo
    external_links:
      - nats
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=posts-api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - analytics-service_rgnetwork

  posts:
    build:
      context: .
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    ports:
      - 3060:3060 
    depends_on: 
      - mongo
    labels:
      - "traefik.enable=false"
    external_links:
      - nats
      - redis
    networks:
      - analytics-service_rgnetwork
  
  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    networks:
      - analytics-service_rgnetwork 

networks:
  analytics-service_rgnetwork:
    external: true

```
